name: 'versioner'
description: 'Git Tag versioning'
inputs:
outputs:
  version:
    description: The version tag
runs:
  using: composite
  steps:
    - name: Generate and tag a new version
      run: |
        version_tag=$(versioner)
        echo $version_tag
        echo "::set-output name=version::$version_tag"
