inputs:
runs:
  using: "docker"
  image: dragosd2000/versioner:latest
  volumes:
    - $GITHUB_WORKSPACE:/repo
  outputs:
    version: ${{ steps.tag.outputs.version }}
  steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Generate and tag a new version
      run: |
        version_tag=$(versioner)
        echo $version_tag
        echo "::set-output name=version::$version_tag"
