name: 'versioner'
description: 'Git Tag versioning'

outputs:
  version:
    value: ${{ steps.semver.outputs.version }}
    description: The version tag
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: DragosDumitrache/versioner
        ref: 2.2.1
    - name: Download versioner
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        ln -s versioner/version.sh /usr/local/bin/the_versioner
#        curl -o the_versioner -L https://github.com/DragosDumitrache/versioner/releases/download/2.2.1/version.sh
        chmod +x /usr/local/bin/the_versioner
    - name: Generate and tag a new version
      id: semver
      working-directory: ${{ github.workspace }}
      shell: bash
      run: |
        version_tag=$(the_versioner)
        echo "Version is: $version_tag"
        echo "version=$(echo $version_tag)" >> $GITHUB_OUTPUT
