name: 'versioner'
description: 'Git Tag versioning'

outputs:
  version:
    value: ${{ steps.semver.outputs.version }}
    description: The version tag
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        path: versioner
    - name: Generate and tag a new version
      id: semver
      shell: bash
      run: |
        version_tag=$(./versioner/version.sh)
        echo "Version is: $version_tag"
        echo "version=$(echo $version_tag)" >> $GITHUB_OUTPUT
