name: 'versioner'
description: 'Git Tag versioning'

outputs:
  version:
    value: ${{ steps.semver.outputs.version }}
    description: The version tag
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        repository: DragosDumitrache/versioner
        ref: 2.2.5
        path: tools
    - name: Get branch names.
      id: branch-names
      uses: tj-actions/branch-names@v8
    - name: Generate and tag a new version on a PR
      id: semver
      working-directory: ${{ github.workspace }}
      shell: bash
      run: |
        version_tag=$(./tools/version.sh ${{ steps.branch-names.outputs.current_branch }})
        echo "Version is: $version_tag"
        echo "version=$(echo $version_tag)" >> $GITHUB_OUTPUT
