name: 'versioner'
description: 'Git Tag versioning'

outputs:
  version:
    value: ${{ steps.semver.outputs.version }}
    description: The version tag
runs:
  using: composite
  steps:
    - name: Download versioner
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        curl -o the_versioner https://github.com/DragosDumitrache/versioner/releases/download/2.1.5/version.sh
        chmod +x the_versioner
    - name: Generate and tag a new version
      id: semver
      working-directory: ${{ github.workspace }}
      shell: bash
      run: |
        cat the_versioner
        ./the_versioner
#        version_tag=$(./the_versioner)
#        echo "Version is: $version_tag"
#        echo "version=$(echo $version_tag)" >> $GITHUB_OUTPUT
